// <auto-generated />
using System;
using BoughtAndHappy.DTO;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BoughtAndHappy.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251214231048_AddOrders")]
    partial class AddOrders
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "product_categories", new[] { "electronics", "clothing", "home_goods", "books", "toys", "groceries", "health_and_beauty", "sports_and_outdoors", "automotive", "computers_and_laptops", "others" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BoughtAndHappy.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("numeric");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("BoughtAndHappy.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("BoughtAndHappy.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<int>("Stock")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Electronics",
                            Name = "Smartphone",
                            Price = 699m,
                            Stock = 20
                        },
                        new
                        {
                            Id = 2,
                            Category = "Electronics",
                            Name = "Tablet",
                            Price = 399m,
                            Stock = 15
                        },
                        new
                        {
                            Id = 3,
                            Category = "Electronics",
                            Name = "Smart TV",
                            Price = 899m,
                            Stock = 8
                        },
                        new
                        {
                            Id = 4,
                            Category = "Electronics",
                            Name = "Bluetooth Speaker",
                            Price = 59m,
                            Stock = 40
                        },
                        new
                        {
                            Id = 5,
                            Category = "Electronics",
                            Name = "Wireless Headphones",
                            Price = 129m,
                            Stock = 30
                        },
                        new
                        {
                            Id = 6,
                            Category = "Electronics",
                            Name = "Power Bank",
                            Price = 39m,
                            Stock = 50
                        },
                        new
                        {
                            Id = 7,
                            Category = "Electronics",
                            Name = "Smart Watch",
                            Price = 199m,
                            Stock = 25
                        },
                        new
                        {
                            Id = 8,
                            Category = "Clothing",
                            Name = "T-Shirt",
                            Price = 15m,
                            Stock = 100
                        },
                        new
                        {
                            Id = 9,
                            Category = "Clothing",
                            Name = "Jeans",
                            Price = 49m,
                            Stock = 60
                        },
                        new
                        {
                            Id = 10,
                            Category = "Clothing",
                            Name = "Hoodie",
                            Price = 39m,
                            Stock = 40
                        },
                        new
                        {
                            Id = 11,
                            Category = "Clothing",
                            Name = "Jacket",
                            Price = 89m,
                            Stock = 25
                        },
                        new
                        {
                            Id = 12,
                            Category = "Clothing",
                            Name = "Sneakers",
                            Price = 79m,
                            Stock = 30
                        },
                        new
                        {
                            Id = 13,
                            Category = "Clothing",
                            Name = "Cap",
                            Price = 12m,
                            Stock = 70
                        },
                        new
                        {
                            Id = 14,
                            Category = "Clothing",
                            Name = "Socks Pack",
                            Price = 10m,
                            Stock = 120
                        },
                        new
                        {
                            Id = 15,
                            Category = "HomeGoods",
                            Name = "Coffee Maker",
                            Price = 99m,
                            Stock = 20
                        },
                        new
                        {
                            Id = 16,
                            Category = "HomeGoods",
                            Name = "Vacuum Cleaner",
                            Price = 199m,
                            Stock = 10
                        },
                        new
                        {
                            Id = 17,
                            Category = "HomeGoods",
                            Name = "Desk Lamp",
                            Price = 29m,
                            Stock = 35
                        },
                        new
                        {
                            Id = 18,
                            Category = "HomeGoods",
                            Name = "Electric Kettle",
                            Price = 49m,
                            Stock = 30
                        },
                        new
                        {
                            Id = 19,
                            Category = "HomeGoods",
                            Name = "Toaster",
                            Price = 39m,
                            Stock = 25
                        },
                        new
                        {
                            Id = 20,
                            Category = "HomeGoods",
                            Name = "Air Humidifier",
                            Price = 59m,
                            Stock = 18
                        },
                        new
                        {
                            Id = 21,
                            Category = "HomeGoods",
                            Name = "Iron",
                            Price = 45m,
                            Stock = 22
                        },
                        new
                        {
                            Id = 22,
                            Category = "Books",
                            Name = "C# Programming Guide",
                            Price = 35m,
                            Stock = 40
                        },
                        new
                        {
                            Id = 23,
                            Category = "Books",
                            Name = "ASP.NET Core in Action",
                            Price = 45m,
                            Stock = 25
                        },
                        new
                        {
                            Id = 24,
                            Category = "Books",
                            Name = "Clean Code",
                            Price = 39m,
                            Stock = 30
                        },
                        new
                        {
                            Id = 25,
                            Category = "Books",
                            Name = "Design Patterns",
                            Price = 49m,
                            Stock = 20
                        },
                        new
                        {
                            Id = 26,
                            Category = "Books",
                            Name = "Refactoring",
                            Price = 44m,
                            Stock = 18
                        },
                        new
                        {
                            Id = 27,
                            Category = "Books",
                            Name = "Domain-Driven Design",
                            Price = 55m,
                            Stock = 15
                        },
                        new
                        {
                            Id = 28,
                            Category = "Books",
                            Name = "Algorithms Handbook",
                            Price = 42m,
                            Stock = 22
                        },
                        new
                        {
                            Id = 29,
                            Category = "Toys",
                            Name = "Lego Set",
                            Price = 59m,
                            Stock = 30
                        },
                        new
                        {
                            Id = 30,
                            Category = "Toys",
                            Name = "Toy Car",
                            Price = 14m,
                            Stock = 80
                        },
                        new
                        {
                            Id = 31,
                            Category = "Toys",
                            Name = "Doll",
                            Price = 25m,
                            Stock = 40
                        },
                        new
                        {
                            Id = 32,
                            Category = "Toys",
                            Name = "Puzzle 1000 pcs",
                            Price = 19m,
                            Stock = 35
                        },
                        new
                        {
                            Id = 33,
                            Category = "Toys",
                            Name = "Board Game",
                            Price = 34m,
                            Stock = 28
                        },
                        new
                        {
                            Id = 34,
                            Category = "Toys",
                            Name = "RC Helicopter",
                            Price = 89m,
                            Stock = 12
                        },
                        new
                        {
                            Id = 35,
                            Category = "Toys",
                            Name = "Action Figure",
                            Price = 22m,
                            Stock = 45
                        },
                        new
                        {
                            Id = 36,
                            Category = "Groceries",
                            Name = "Milk 1L",
                            Price = 2m,
                            Stock = 200
                        },
                        new
                        {
                            Id = 37,
                            Category = "Groceries",
                            Name = "Bread",
                            Price = 1.5m,
                            Stock = 150
                        },
                        new
                        {
                            Id = 38,
                            Category = "Groceries",
                            Name = "Eggs 10 pcs",
                            Price = 3m,
                            Stock = 120
                        },
                        new
                        {
                            Id = 39,
                            Category = "Groceries",
                            Name = "Cheese",
                            Price = 6m,
                            Stock = 80
                        },
                        new
                        {
                            Id = 40,
                            Category = "Groceries",
                            Name = "Chicken Breast",
                            Price = 7m,
                            Stock = 60
                        },
                        new
                        {
                            Id = 41,
                            Category = "Groceries",
                            Name = "Rice 1kg",
                            Price = 2.5m,
                            Stock = 140
                        },
                        new
                        {
                            Id = 42,
                            Category = "Groceries",
                            Name = "Pasta",
                            Price = 1.8m,
                            Stock = 160
                        },
                        new
                        {
                            Id = 43,
                            Category = "HealthAndBeauty",
                            Name = "Shampoo",
                            Price = 8m,
                            Stock = 70
                        },
                        new
                        {
                            Id = 44,
                            Category = "HealthAndBeauty",
                            Name = "Conditioner",
                            Price = 8m,
                            Stock = 65
                        },
                        new
                        {
                            Id = 45,
                            Category = "HealthAndBeauty",
                            Name = "Toothpaste",
                            Price = 3m,
                            Stock = 120
                        },
                        new
                        {
                            Id = 46,
                            Category = "HealthAndBeauty",
                            Name = "Body Lotion",
                            Price = 10m,
                            Stock = 50
                        },
                        new
                        {
                            Id = 47,
                            Category = "HealthAndBeauty",
                            Name = "Face Cream",
                            Price = 15m,
                            Stock = 40
                        },
                        new
                        {
                            Id = 48,
                            Category = "HealthAndBeauty",
                            Name = "Hand Soap",
                            Price = 2.5m,
                            Stock = 150
                        },
                        new
                        {
                            Id = 49,
                            Category = "HealthAndBeauty",
                            Name = "Vitamin C",
                            Price = 12m,
                            Stock = 55
                        },
                        new
                        {
                            Id = 50,
                            Category = "SportsAndOutdoors",
                            Name = "Football",
                            Price = 25m,
                            Stock = 30
                        },
                        new
                        {
                            Id = 51,
                            Category = "SportsAndOutdoors",
                            Name = "Basketball",
                            Price = 27m,
                            Stock = 28
                        },
                        new
                        {
                            Id = 52,
                            Category = "SportsAndOutdoors",
                            Name = "Yoga Mat",
                            Price = 20m,
                            Stock = 45
                        },
                        new
                        {
                            Id = 53,
                            Category = "SportsAndOutdoors",
                            Name = "Dumbbells Set",
                            Price = 60m,
                            Stock = 18
                        },
                        new
                        {
                            Id = 54,
                            Category = "SportsAndOutdoors",
                            Name = "Tennis Racket",
                            Price = 75m,
                            Stock = 15
                        },
                        new
                        {
                            Id = 55,
                            Category = "SportsAndOutdoors",
                            Name = "Camping Tent",
                            Price = 120m,
                            Stock = 10
                        },
                        new
                        {
                            Id = 56,
                            Category = "SportsAndOutdoors",
                            Name = "Sleeping Bag",
                            Price = 45m,
                            Stock = 22
                        },
                        new
                        {
                            Id = 57,
                            Category = "Automotive",
                            Name = "Car Battery",
                            Price = 110m,
                            Stock = 12
                        },
                        new
                        {
                            Id = 58,
                            Category = "Automotive",
                            Name = "Engine Oil",
                            Price = 35m,
                            Stock = 40
                        },
                        new
                        {
                            Id = 59,
                            Category = "Automotive",
                            Name = "Windshield Wipers",
                            Price = 18m,
                            Stock = 50
                        },
                        new
                        {
                            Id = 60,
                            Category = "Automotive",
                            Name = "Car Vacuum Cleaner",
                            Price = 45m,
                            Stock = 25
                        },
                        new
                        {
                            Id = 61,
                            Category = "Automotive",
                            Name = "Tire Pressure Gauge",
                            Price = 12m,
                            Stock = 60
                        },
                        new
                        {
                            Id = 62,
                            Category = "Automotive",
                            Name = "Jump Starter",
                            Price = 90m,
                            Stock = 14
                        },
                        new
                        {
                            Id = 63,
                            Category = "Automotive",
                            Name = "Car Phone Holder",
                            Price = 15m,
                            Stock = 70
                        },
                        new
                        {
                            Id = 64,
                            Category = "ComputersAndLaptops",
                            Name = "Laptop",
                            Price = 900m,
                            Stock = 10
                        },
                        new
                        {
                            Id = 65,
                            Category = "ComputersAndLaptops",
                            Name = "Gaming PC",
                            Price = 1500m,
                            Stock = 6
                        },
                        new
                        {
                            Id = 66,
                            Category = "ComputersAndLaptops",
                            Name = "Mechanical Keyboard",
                            Price = 120m,
                            Stock = 20
                        },
                        new
                        {
                            Id = 67,
                            Category = "ComputersAndLaptops",
                            Name = "Wireless Mouse",
                            Price = 40m,
                            Stock = 35
                        },
                        new
                        {
                            Id = 68,
                            Category = "ComputersAndLaptops",
                            Name = "27\" Monitor",
                            Price = 300m,
                            Stock = 14
                        },
                        new
                        {
                            Id = 69,
                            Category = "ComputersAndLaptops",
                            Name = "USB-C Hub",
                            Price = 45m,
                            Stock = 50
                        },
                        new
                        {
                            Id = 70,
                            Category = "ComputersAndLaptops",
                            Name = "External SSD 1TB",
                            Price = 150m,
                            Stock = 18
                        },
                        new
                        {
                            Id = 71,
                            Category = "Others",
                            Name = "Gift Card",
                            Price = 50m,
                            Stock = 100
                        },
                        new
                        {
                            Id = 72,
                            Category = "Others",
                            Name = "Notebook",
                            Price = 5m,
                            Stock = 200
                        },
                        new
                        {
                            Id = 73,
                            Category = "Others",
                            Name = "Pen Set",
                            Price = 7m,
                            Stock = 180
                        },
                        new
                        {
                            Id = 74,
                            Category = "Others",
                            Name = "Backpack",
                            Price = 45m,
                            Stock = 35
                        },
                        new
                        {
                            Id = 75,
                            Category = "Others",
                            Name = "Travel Mug",
                            Price = 18m,
                            Stock = 60
                        });
                });

            modelBuilder.Entity("BoughtAndHappy.Models.OrderItem", b =>
                {
                    b.HasOne("BoughtAndHappy.Models.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("BoughtAndHappy.Models.Order", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
